### ISSUE TITLE
[Question] Why rewards are recomputed by ags_fut with goals_fut?

### ISSUE THREAD

**Issue by RyoKobun** [spitis/mrl#21]
I might not fully understand the code. If possible, could anyone explain how the code does HER in online_her_buffer.py?

> ags = np.concatenate([ags, ags_fut, ags_act, ags_ach, ags_beh], 0)
        goals = np.concatenate([goals, goals_fut, goals_act, goals_ach, goals_beh], 0)

> rewards = self.goal_reward(ags, goals, {'s':states, 'a':actions, 'ns':next_states}).reshape(-1, 1).astype(np.float32)

From my understanding, it should be [ags,...] and [ags_fut,...], so that the agent could recompute a virtual reward to learn from failed experiences.
Or maybe my understanding is wrong?

Also, why the rewards from real batch are not used any more? All rewards are just replaced by recomputed rewards?

**Comment by spitis** [comment]
Hi Ryo, yes the rewards in that code snippet are recomputed for the entire
batch including real data. You will want to change this if you don't know
the ground truth reward function.

I'm not following your first question.

**Comment by RyoKobun** [comment]
Thank you for your reply, Pitis!
Maybe my expression was not clear enough. What confuses me is: In the concatenated ags and goals, the ags_fut recompute rewards with goals_fut, where is the relabeling process? If future ags compute rewards with future goals, aren't the rewards just future rewards in the future buffer?

**Comment by spitis** [comment]
Hi, so there are two parts to the relabeling: first we relabel the goal
itself from a normal goal to the "goals_fut". This happens when we sample
from the replay buffer (it just samples the relabeled goals directly).

The ags_fut are just the achieved goal for the transition that was sampled
together w the new goals.

Then in the second part you posted, we recompute the reward itself based on
what was actually achieved in the transition (ags_fut) and the relabeled
goals (goals_fut).

**Comment by RyoKobun** [comment]
Oh, thank you for the explanation! Now I understand the whole process. I'll close this issue.
